# Generated by Django 3.2.4 on 2021-06-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='image',
        ),
    ]
